test:
  user:
    name: this is the provider-dev

server:
  port: 8081
spring:
  application:
    name: provider-server
eureka:
  instance:
    hostname: 127.0.0.1
    appname: ${spring.application.name}
  client:
    registry-fetch-interval-seconds: 10
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/